<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.threevictors.aws.priceeye.exp</groupId>
    <artifactId>pe-engines-taxes-exp</artifactId>
    <version>0.01-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>pe-engines-taxes-exp</name>

    <url>http://www.3victors.com</url>

    <modules>
        <module>pe-engines-taxes-common</module>
        <module>pe-engines-taxes-core</module>
        <module>pe-engines-taxes-spark</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <version.priceeyev2>0.122</version.priceeyev2>
        <version.3v.config.reader>0.58</version.3v.config.reader>

        <!-- greater than version 3.1 maven required -->
        <version.plugin.enforcer>3.4.1</version.plugin.enforcer>
        <version.plugin.enforcer.enforce>(3.1,)</version.plugin.enforcer.enforce>
        <version.velocity>2.4</version.velocity>
        <version.soap>1.4.0</version.soap>
        <version.json-path>2.9.0</version.json-path>
        <version.slf4j>2.0.16</version.slf4j>
        <version.amazon.aws.sdk.v2>2.30.30</version.amazon.aws.sdk.v2>
        <version.mysql.connector>9.2.0</version.mysql.connector>
        <version.spark>3.3.2</version.spark>
        <version.kryo>5.5.0</version.kryo>
        <version.log4j>2.24.3</version.log4j>

        <git.directory>~/git</git.directory>
        <docker.pushRegistry>732267085676.dkr.ecr.us-east-1.amazonaws.com</docker.pushRegistry>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <maven.compiler.release>11</maven.compiler.release>
        <maven.compiler.verbose>false</maven.compiler.verbose>
        <maven.compiler.debug>false</maven.compiler.debug>
        <maven.compiler.showDeprecation>false</maven.compiler.showDeprecation>
        <maven.compiler.showWarnings>false</maven.compiler.showWarnings>
        <maven.build.timestamp.format>yyyyMMdd_HHmm</maven.build.timestamp.format>
        <buildNumber>${maven.build.timestamp}</buildNumber>
        <build.timestamp>${maven.build.timestamp}</build.timestamp>

        <minimize.resources>false</minimize.resources>
    </properties>

    <distributionManagement>
        <repository>
            <id>atpco-3v-3V-ATP</id>
            <name>atpco-3v-3V-ATP</name>
            <url>https://atpco-3v-590183652635.d.codeartifact.us-east-1.amazonaws.com/maven/3V-ATP/</url>
        </repository>
    </distributionManagement>

    <scm>
        <connection>scm:git:git@github.com:atp1pxj/pe-engines-taxes-exp.git</connection>
        <url>scm:git:git@github.com:atp1pxj/pe-engines-taxes-exp.git</url>
        <developerConnection>scm:git:git@github.com:atp1pxj/pe-engines-taxes-exp</developerConnection>
        <tag>HEAD</tag>
    </scm>

    <repositories>
        <!-- Maven Central Repository -->
        <repository>
            <id>central</id>
            <name>Maven Central</name>
            <url>https://repo.maven.apache.org/maven2</url>
            <releases><enabled>true</enabled></releases>
            <snapshots><enabled>false</enabled></snapshots>
        </repository>
        <!-- repo config for priceeye related artifacts-->
        <repository>
            <id>atpco-3v-3V-ATP</id>
            <name>atpco-3v-3V-ATP</name>
            <url>https://atpco-3v-590183652635.d.codeartifact.us-east-1.amazonaws.com/maven/3V-ATP/</url>
            <releases><enabled>true</enabled></releases>
            <snapshots><enabled>true</enabled></snapshots>
        </repository>
        <!-- repo config for Engine related artifacts-->
        <repository>
            <id>Nexus</id>
            <name>ATPCO Nexus Maven Repository</name>
            <url>http://artmgt01.atpco.org:8081/repository/maven-public/</url>
            <layout>default</layout>
        </repository>
        <repository>
            <id>Maven_Central</id>
            <name>ATPCO Nexus Maven Central Repository</name>
            <url>http://artmgt01.atpco.org:8081/repository/maven-central/</url>
            <layout>default</layout>
        </repository>
        <repository>
            <id>Nexus_RandD</id>
            <name>ATPCO Nexus Maven Repository</name>
            <url>http://artmgt01.atpco.org:8081/repository/maven-releases/</url>
            <layout>default</layout>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <!-- Internal module dependencies -->
            <dependency>
                <groupId>com.threevictors.aws.priceeye.exp</groupId>
                <artifactId>pe-engines-taxes-common</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.threevictors.aws.priceeye.exp</groupId>
                <artifactId>pe-engines-taxes-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.threevictors.aws.priceeye.exp</groupId>
                <artifactId>pe-engines-taxes-spark</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- 3V CONFIGREADER Dependency-->
            <dependency>
                <groupId>com.threevictors.aws.configreader</groupId>
                <artifactId>threevictors-configuration-reader-heavy</artifactId>
                <version>${version.3v.config.reader}</version>
            </dependency>

            <!-- PriceEye dependencies -->
            <dependency>
                <groupId>com.threevictors.aws.priceeye</groupId>
                <artifactId>threevictors-priceeye-data</artifactId>
                <version>${version.priceeyev2}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.apache.logging.log4j</groupId>
                        <artifactId>log4j-1.2-api</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>log4j-over-slf4j</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>com.threevictors.aws.priceeye</groupId>
                <artifactId>threevictors-priceeye-common</artifactId>
                <version>${version.priceeyev2}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.apache.logging.log4j</groupId>
                        <artifactId>log4j-1.2-api</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>log4j-over-slf4j</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            <!-- Service Fee Engine -->
            <dependency>
                <groupId>net.atpco.engine.servicefees</groupId>
                <artifactId>service-fee-engine</artifactId>
                <version>26.2.3</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.apache.logging.log4j</groupId>
                        <artifactId>log4j-slf4j-impl</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-reload4j</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.logging.log4j</groupId>
                        <artifactId>log4j-to-slf4j</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>ch.qos.logback</groupId>
                        <artifactId>logback-classic</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>ch.qos.logback</groupId>
                        <artifactId>logback-core</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>ch.qos.logback</groupId>
                        <artifactId>logback-access</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            <!-- Utility dependencies -->
            <dependency>
                <groupId>org.apache.velocity</groupId>
                <artifactId>velocity-engine-core</artifactId>
                <version>${version.velocity}</version>
            </dependency>
            <dependency>
                <groupId>javax.xml.soap</groupId>
                <artifactId>javax.xml.soap-api</artifactId>
                <version>${version.soap}</version>
            </dependency>
            <dependency>
                <groupId>com.jayway.jsonpath</groupId>
                <artifactId>json-path</artifactId>
                <version>${version.json-path}</version>
            </dependency>
            <dependency>
                <groupId>com.threevictors</groupId>
                <artifactId>threevictors-common-database-data-access-aurora-metadata</artifactId>
                <version>0.178</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.apache.logging.log4j</groupId>
                        <artifactId>log4j-1.2-api</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>log4j-over-slf4j</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>com.mysql</groupId>
                <artifactId>mysql-connector-j</artifactId>
                <version>${version.mysql.connector}</version>
            </dependency>
            <dependency>
                <groupId>com.opencsv</groupId>
                <artifactId>opencsv</artifactId>
                <version>5.11</version>
            </dependency>

            <!-- Logging dependencies -->
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-api</artifactId>
                <version>${version.log4j}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-core</artifactId>
                <version>${version.log4j}</version>
            </dependency>

            <!-- Kryo serialization -->
            <dependency>
                <groupId>com.esotericsoftware</groupId>
                <artifactId>kryo</artifactId>
                <version>${version.kryo}</version>
            </dependency>

            <!-- AWS SDK -->
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>bom</artifactId>
                <version>${version.amazon.aws.sdk.v2}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>apache-client</artifactId>
                <version>${version.amazon.aws.sdk.v2}</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>auth</artifactId>
                <version>${version.amazon.aws.sdk.v2}</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>cloudwatch</artifactId>
                <version>${version.amazon.aws.sdk.v2}</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>ecs</artifactId>
                <version>${version.amazon.aws.sdk.v2}</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>ec2</artifactId>
                <version>${version.amazon.aws.sdk.v2}</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>firehose</artifactId>
                <version>${version.amazon.aws.sdk.v2}</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>s3</artifactId>
                <version>${version.amazon.aws.sdk.v2}</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>sagemaker</artifactId>
                <version>${version.amazon.aws.sdk.v2}</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>sagemakerruntime</artifactId>
                <version>${version.amazon.aws.sdk.v2}</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>sdk-core</artifactId>
                <version>${version.amazon.aws.sdk.v2}</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>ses</artifactId>
                <version>${version.amazon.aws.sdk.v2}</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>sns</artifactId>
                <version>${version.amazon.aws.sdk.v2}</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>sqs</artifactId>
                <version>${version.amazon.aws.sdk.v2}</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>sts</artifactId>
                <version>${version.amazon.aws.sdk.v2}</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>url-connection-client</artifactId>
                <version>${version.amazon.aws.sdk.v2}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>3.5.1</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.11.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>3.3.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.3.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>${version.plugin.enforcer}</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <executions>
                    <execution>
                        <id>enforce-maven</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <requireMavenVersion>
                                    <version>${version.plugin.enforcer.enforce}</version>
                                </requireMavenVersion>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>atpco-3v-3V-ATP</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <repositories>
                <repository>
                    <id>atpco-3v-3V-ATP</id>
                    <url>https://atpco-3v-590183652635.d.codeartifact.us-east-1.amazonaws.com/maven/3V-ATP/</url>
                </repository>
            </repositories>
        </profile>
        <profile>
            <id>snapshot</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <distributionManagement>
                <snapshotRepository>
                    <id>maven-snapshots</id>
                    <name>Local Nexus Snapshots</name>
                    <url>http://artmgt01.atpco.org:8081/repository/maven-snapshots/</url>
                </snapshotRepository>
            </distributionManagement>
        </profile>
        <profile>
            <id>release</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <distributionManagement>
                <repository>
                    <id>maven-releases</id>
                    <name>Local Nexus Releases</name>
                    <url>http://artmgt01.atpco.org:8081/repository/maven-releases/</url>
                </repository>
            </distributionManagement>
        </profile>
    </profiles>
</project>